replicaCount: 1

fullname: github-observer
namespace: observability
ingress:
  host: github-observer.local

image:
  repository: ghcr.io/otto-wagner/github-observer
  tag: latest

service:
    port: 8443

secret:
  key: github-token
  value: "token"

env:
  - name: "SSL_ACTIVATE"
    value: "false"
  - name: "SSL_CERT"
    value: "./certs/server.cert"
  - name: "SSL_KEY"
    value: "./certs/server.key"
  - name: "APP_LISTENADDRESS"
    value: "0.0.0.0:8080"
  - name: "APP_TRUSTEDPROXIES"
    value: null
  - name: "APP_MODE"
    value: "debug"
  - name: "APP_WATCHER"
    value: "true"
  - name: "APP_LOGS"
    value: "executor,watcher,listener"
  - name: "APP_EXECUTORS"
    value: "logging,prometheus"
  - name: "REPOSITORIES"
    value: "otto-wagner/github-observer@main"
