// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	github "github.com/google/go-github/v61/github"
	mock "github.com/stretchr/testify/mock"
)

// IExecutor is an autogenerated mock type for the IExecutor type
type IExecutor struct {
	mock.Mock
}

// CheckRunEvent provides a mock function with given fields: _a0
func (_m *IExecutor) CheckRunEvent(_a0 github.CheckRunEvent) {
	_m.Called(_a0)
}

// PullRequestEvent provides a mock function with given fields: _a0
func (_m *IExecutor) PullRequestEvent(_a0 github.PullRequestEvent) {
	_m.Called(_a0)
}

// PullRequestReviewEvent provides a mock function with given fields: _a0
func (_m *IExecutor) PullRequestReviewEvent(_a0 github.PullRequestReviewEvent) {
	_m.Called(_a0)
}

// NewIExecutor creates a new instance of IExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExecutor {
	mock := &IExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
