// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	core "github-observer/internal/core"

	mock "github.com/stretchr/testify/mock"
)

// IMemory is an autogenerated mock type for the IMemory type
type IMemory struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *IMemory) Get(_a0 core.WorkflowRun) (core.WorkflowRun, bool) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 core.WorkflowRun
	var r1 bool
	if rf, ok := ret.Get(0).(func(core.WorkflowRun) (core.WorkflowRun, bool)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(core.WorkflowRun) core.WorkflowRun); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(core.WorkflowRun)
	}

	if rf, ok := ret.Get(1).(func(core.WorkflowRun) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetPR provides a mock function with given fields: _a0
func (_m *IMemory) GetPR(_a0 core.GitPullRequest) (core.GitPullRequest, bool) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPR")
	}

	var r0 core.GitPullRequest
	var r1 bool
	if rf, ok := ret.Get(0).(func(core.GitPullRequest) (core.GitPullRequest, bool)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(core.GitPullRequest) core.GitPullRequest); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(core.GitPullRequest)
	}

	if rf, ok := ret.Get(1).(func(core.GitPullRequest) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0
func (_m *IMemory) Store(_a0 core.WorkflowRun) {
	_m.Called(_a0)
}

// StorePR provides a mock function with given fields: _a0
func (_m *IMemory) StorePR(_a0 core.GitPullRequest) {
	_m.Called(_a0)
}

// NewIMemory creates a new instance of IMemory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMemory(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMemory {
	mock := &IMemory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
