controller:
  service:
    internal:
      enabled: false
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "internal"
    external:
      enabled: false
    externalPorts:
      http: 80
      https: 443
    targetPorts:
      http: 80
      https: 8080
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - host: github-observer.local
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: github-observer
              servicePort: 8080