services:
  github-observer:
#    image: ghcr.io/otto-wagner/github-observer:latest
    build:
      context: .
      dockerfile: Dockerfile
    user: observer
    environment:
      - USER_UID=1000
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8443:8443"
    networks:
        - github-observer

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - github-observer
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - github-observer

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - github-observer
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

#  ngrok:
#    image: ngrok/ngrok:latest
#    ports:
#      - "4040:4040"
#    networks:
#      - github-observer
#    command:
#      - "start"
#      - "--all"
#      - "--config"
#      - "/etc/ngrok.yml"
#    environment:
#      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
#    volumes:
#      - ./ngrok/etc/ngrok.yml:/etc/ngrok.yml
#    depends_on:
#        - github-observer
#        - prometheus
#        - grafana

volumes:
  grafana_data:

networks:
  github-observer:
