services:
  observer:
    build:
      context: .
      dockerfile: deployments/observer/Dockerfile
    container_name: observer
    env_file:
      - .env
    command: [ "./observer", "server" ]
    ports:
      - "8443:8443"
    networks:
      - observer_net
    restart: unless-stopped

networks:
  observer_net:
    driver: bridge
