services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f 'http://localhost:3100/ready' | grep '^ready$'"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - ./loki:/etc/loki
      - ./loki/index:/loki/index
      - ./loki/boltdb-cache:/loki/boltdb-cache
      - ./loki/chunks:/loki/chunks
    networks:
      - github-observer

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/:/fluent-bit/etc/
      - ./var/log:/var/log
    networks:
      - github-observer
    depends_on:
      - loki

  github-observer:
    image: ghcr.io/otto-wagner/github-observer:latest
    container_name: github-observer
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
    command: ["./observer", "server", "run"]
    volumes:
      - ./conf:/conf
      - ./var/log:/var/log
    user: observer
    environment:
      - USER_UID=1000
    ports:
      - "8443:8443"
    networks:
      - github-observer
    depends_on:
      - loki

  #  ngrok:
  #    image: ngrok/ngrok:latest
  #    ports:
  #      - "4040:4040"
  #    networks:
  #      - github-observer
  #    command:
  #      - "start"
  #      - "--all"
  #      - "--config"
  #      - "/etc/ngrok.yml"
  #    volumes:
  #      - ./ngrok/etc/ngrok.yml:/etc/ngrok.yml
  #    depends_on:
  #      - github-observer

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - github-observer
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - github-observer

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - github-observer
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
      - loki

volumes:
  grafana_data:

networks:
  github-observer: