// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	"github.com/google/go-github/v73/github"
	"github.com/otto-wagner/github-observer/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIExecutor creates a new instance of MockIExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIExecutor {
	mock := &MockIExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIExecutor is an autogenerated mock type for the IExecutor type
type MockIExecutor struct {
	mock.Mock
}

type MockIExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIExecutor) EXPECT() *MockIExecutor_Expecter {
	return &MockIExecutor_Expecter{mock: &_m.Mock}
}

// EventPullRequest provides a mock function for the type MockIExecutor
func (_mock *MockIExecutor) EventPullRequest(pullRequestEvent github.PullRequestEvent) {
	_mock.Called(pullRequestEvent)
	return
}

// MockIExecutor_EventPullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventPullRequest'
type MockIExecutor_EventPullRequest_Call struct {
	*mock.Call
}

// EventPullRequest is a helper method to define mock.On call
//   - pullRequestEvent github.PullRequestEvent
func (_e *MockIExecutor_Expecter) EventPullRequest(pullRequestEvent interface{}) *MockIExecutor_EventPullRequest_Call {
	return &MockIExecutor_EventPullRequest_Call{Call: _e.mock.On("EventPullRequest", pullRequestEvent)}
}

func (_c *MockIExecutor_EventPullRequest_Call) Run(run func(pullRequestEvent github.PullRequestEvent)) *MockIExecutor_EventPullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 github.PullRequestEvent
		if args[0] != nil {
			arg0 = args[0].(github.PullRequestEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIExecutor_EventPullRequest_Call) Return() *MockIExecutor_EventPullRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIExecutor_EventPullRequest_Call) RunAndReturn(run func(pullRequestEvent github.PullRequestEvent)) *MockIExecutor_EventPullRequest_Call {
	_c.Run(run)
	return _c
}

// EventPullRequestReview provides a mock function for the type MockIExecutor
func (_mock *MockIExecutor) EventPullRequestReview(pullRequestReviewEvent github.PullRequestReviewEvent) {
	_mock.Called(pullRequestReviewEvent)
	return
}

// MockIExecutor_EventPullRequestReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventPullRequestReview'
type MockIExecutor_EventPullRequestReview_Call struct {
	*mock.Call
}

// EventPullRequestReview is a helper method to define mock.On call
//   - pullRequestReviewEvent github.PullRequestReviewEvent
func (_e *MockIExecutor_Expecter) EventPullRequestReview(pullRequestReviewEvent interface{}) *MockIExecutor_EventPullRequestReview_Call {
	return &MockIExecutor_EventPullRequestReview_Call{Call: _e.mock.On("EventPullRequestReview", pullRequestReviewEvent)}
}

func (_c *MockIExecutor_EventPullRequestReview_Call) Run(run func(pullRequestReviewEvent github.PullRequestReviewEvent)) *MockIExecutor_EventPullRequestReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 github.PullRequestReviewEvent
		if args[0] != nil {
			arg0 = args[0].(github.PullRequestReviewEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIExecutor_EventPullRequestReview_Call) Return() *MockIExecutor_EventPullRequestReview_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIExecutor_EventPullRequestReview_Call) RunAndReturn(run func(pullRequestReviewEvent github.PullRequestReviewEvent)) *MockIExecutor_EventPullRequestReview_Call {
	_c.Run(run)
	return _c
}

// EventWorkflowRun provides a mock function for the type MockIExecutor
func (_mock *MockIExecutor) EventWorkflowRun(workflowRunEvent github.WorkflowRunEvent) {
	_mock.Called(workflowRunEvent)
	return
}

// MockIExecutor_EventWorkflowRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventWorkflowRun'
type MockIExecutor_EventWorkflowRun_Call struct {
	*mock.Call
}

// EventWorkflowRun is a helper method to define mock.On call
//   - workflowRunEvent github.WorkflowRunEvent
func (_e *MockIExecutor_Expecter) EventWorkflowRun(workflowRunEvent interface{}) *MockIExecutor_EventWorkflowRun_Call {
	return &MockIExecutor_EventWorkflowRun_Call{Call: _e.mock.On("EventWorkflowRun", workflowRunEvent)}
}

func (_c *MockIExecutor_EventWorkflowRun_Call) Run(run func(workflowRunEvent github.WorkflowRunEvent)) *MockIExecutor_EventWorkflowRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 github.WorkflowRunEvent
		if args[0] != nil {
			arg0 = args[0].(github.WorkflowRunEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIExecutor_EventWorkflowRun_Call) Return() *MockIExecutor_EventWorkflowRun_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIExecutor_EventWorkflowRun_Call) RunAndReturn(run func(workflowRunEvent github.WorkflowRunEvent)) *MockIExecutor_EventWorkflowRun_Call {
	_c.Run(run)
	return _c
}

// Handler provides a mock function for the type MockIExecutor
func (_mock *MockIExecutor) Handler() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockIExecutor_Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handler'
type MockIExecutor_Handler_Call struct {
	*mock.Call
}

// Handler is a helper method to define mock.On call
func (_e *MockIExecutor_Expecter) Handler() *MockIExecutor_Handler_Call {
	return &MockIExecutor_Handler_Call{Call: _e.mock.On("Handler")}
}

func (_c *MockIExecutor_Handler_Call) Run(run func()) *MockIExecutor_Handler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIExecutor_Handler_Call) Return(handlerFunc gin.HandlerFunc) *MockIExecutor_Handler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockIExecutor_Handler_Call) RunAndReturn(run func() gin.HandlerFunc) *MockIExecutor_Handler_Call {
	_c.Call.Return(run)
	return _c
}

// LastWorkflows provides a mock function for the type MockIExecutor
func (_mock *MockIExecutor) LastWorkflows(repository core.Repository, workflowRuns []*github.WorkflowRun) {
	_mock.Called(repository, workflowRuns)
	return
}

// MockIExecutor_LastWorkflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastWorkflows'
type MockIExecutor_LastWorkflows_Call struct {
	*mock.Call
}

// LastWorkflows is a helper method to define mock.On call
//   - repository core.Repository
//   - workflowRuns []*github.WorkflowRun
func (_e *MockIExecutor_Expecter) LastWorkflows(repository interface{}, workflowRuns interface{}) *MockIExecutor_LastWorkflows_Call {
	return &MockIExecutor_LastWorkflows_Call{Call: _e.mock.On("LastWorkflows", repository, workflowRuns)}
}

func (_c *MockIExecutor_LastWorkflows_Call) Run(run func(repository core.Repository, workflowRuns []*github.WorkflowRun)) *MockIExecutor_LastWorkflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Repository
		if args[0] != nil {
			arg0 = args[0].(core.Repository)
		}
		var arg1 []*github.WorkflowRun
		if args[1] != nil {
			arg1 = args[1].([]*github.WorkflowRun)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIExecutor_LastWorkflows_Call) Return() *MockIExecutor_LastWorkflows_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIExecutor_LastWorkflows_Call) RunAndReturn(run func(repository core.Repository, workflowRuns []*github.WorkflowRun)) *MockIExecutor_LastWorkflows_Call {
	_c.Run(run)
	return _c
}

// PullRequests provides a mock function for the type MockIExecutor
func (_mock *MockIExecutor) PullRequests(repository core.Repository, pullRequests []*github.PullRequest) {
	_mock.Called(repository, pullRequests)
	return
}

// MockIExecutor_PullRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullRequests'
type MockIExecutor_PullRequests_Call struct {
	*mock.Call
}

// PullRequests is a helper method to define mock.On call
//   - repository core.Repository
//   - pullRequests []*github.PullRequest
func (_e *MockIExecutor_Expecter) PullRequests(repository interface{}, pullRequests interface{}) *MockIExecutor_PullRequests_Call {
	return &MockIExecutor_PullRequests_Call{Call: _e.mock.On("PullRequests", repository, pullRequests)}
}

func (_c *MockIExecutor_PullRequests_Call) Run(run func(repository core.Repository, pullRequests []*github.PullRequest)) *MockIExecutor_PullRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Repository
		if args[0] != nil {
			arg0 = args[0].(core.Repository)
		}
		var arg1 []*github.PullRequest
		if args[1] != nil {
			arg1 = args[1].([]*github.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIExecutor_PullRequests_Call) Return() *MockIExecutor_PullRequests_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIExecutor_PullRequests_Call) RunAndReturn(run func(repository core.Repository, pullRequests []*github.PullRequest)) *MockIExecutor_PullRequests_Call {
	_c.Run(run)
	return _c
}
