// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIListener creates a new instance of MockIListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIListener {
	mock := &MockIListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIListener is an autogenerated mock type for the IListener type
type MockIListener struct {
	mock.Mock
}

type MockIListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIListener) EXPECT() *MockIListener_Expecter {
	return &MockIListener_Expecter{mock: &_m.Mock}
}

// PullRequest provides a mock function for the type MockIListener
func (_mock *MockIListener) PullRequest(context *gin.Context) {
	_mock.Called(context)
	return
}

// MockIListener_PullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullRequest'
type MockIListener_PullRequest_Call struct {
	*mock.Call
}

// PullRequest is a helper method to define mock.On call
//   - context *gin.Context
func (_e *MockIListener_Expecter) PullRequest(context interface{}) *MockIListener_PullRequest_Call {
	return &MockIListener_PullRequest_Call{Call: _e.mock.On("PullRequest", context)}
}

func (_c *MockIListener_PullRequest_Call) Run(run func(context *gin.Context)) *MockIListener_PullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIListener_PullRequest_Call) Return() *MockIListener_PullRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIListener_PullRequest_Call) RunAndReturn(run func(context *gin.Context)) *MockIListener_PullRequest_Call {
	_c.Run(run)
	return _c
}

// PullRequestReview provides a mock function for the type MockIListener
func (_mock *MockIListener) PullRequestReview(context *gin.Context) {
	_mock.Called(context)
	return
}

// MockIListener_PullRequestReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullRequestReview'
type MockIListener_PullRequestReview_Call struct {
	*mock.Call
}

// PullRequestReview is a helper method to define mock.On call
//   - context *gin.Context
func (_e *MockIListener_Expecter) PullRequestReview(context interface{}) *MockIListener_PullRequestReview_Call {
	return &MockIListener_PullRequestReview_Call{Call: _e.mock.On("PullRequestReview", context)}
}

func (_c *MockIListener_PullRequestReview_Call) Run(run func(context *gin.Context)) *MockIListener_PullRequestReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIListener_PullRequestReview_Call) Return() *MockIListener_PullRequestReview_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIListener_PullRequestReview_Call) RunAndReturn(run func(context *gin.Context)) *MockIListener_PullRequestReview_Call {
	_c.Run(run)
	return _c
}

// Workflow provides a mock function for the type MockIListener
func (_mock *MockIListener) Workflow(context *gin.Context) {
	_mock.Called(context)
	return
}

// MockIListener_Workflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workflow'
type MockIListener_Workflow_Call struct {
	*mock.Call
}

// Workflow is a helper method to define mock.On call
//   - context *gin.Context
func (_e *MockIListener_Expecter) Workflow(context interface{}) *MockIListener_Workflow_Call {
	return &MockIListener_Workflow_Call{Call: _e.mock.On("Workflow", context)}
}

func (_c *MockIListener_Workflow_Call) Run(run func(context *gin.Context)) *MockIListener_Workflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIListener_Workflow_Call) Return() *MockIListener_Workflow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIListener_Workflow_Call) RunAndReturn(run func(context *gin.Context)) *MockIListener_Workflow_Call {
	_c.Run(run)
	return _c
}
