// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/otto-wagner/github-observer/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIWatcher creates a new instance of MockIWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWatcher {
	mock := &MockIWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIWatcher is an autogenerated mock type for the IWatcher type
type MockIWatcher struct {
	mock.Mock
}

type MockIWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIWatcher) EXPECT() *MockIWatcher_Expecter {
	return &MockIWatcher_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockIWatcher
func (_mock *MockIWatcher) Start() {
	_mock.Called()
	return
}

// MockIWatcher_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIWatcher_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockIWatcher_Expecter) Start() *MockIWatcher_Start_Call {
	return &MockIWatcher_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockIWatcher_Start_Call) Run(run func()) *MockIWatcher_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIWatcher_Start_Call) Return() *MockIWatcher_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIWatcher_Start_Call) RunAndReturn(run func()) *MockIWatcher_Start_Call {
	_c.Run(run)
	return _c
}

// PullRequests provides a mock function for the type MockIWatcher
func (_mock *MockIWatcher) PullRequests(repository core.Repository) {
	_mock.Called(repository)
	return
}

// MockIWatcher_PullRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullRequests'
type MockIWatcher_PullRequests_Call struct {
	*mock.Call
}

// PullRequests is a helper method to define mock.On call
//   - repository core.Repository
func (_e *MockIWatcher_Expecter) PullRequests(repository interface{}) *MockIWatcher_PullRequests_Call {
	return &MockIWatcher_PullRequests_Call{Call: _e.mock.On("PullRequests", repository)}
}

func (_c *MockIWatcher_PullRequests_Call) Run(run func(repository core.Repository)) *MockIWatcher_PullRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Repository
		if args[0] != nil {
			arg0 = args[0].(core.Repository)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIWatcher_PullRequests_Call) Return() *MockIWatcher_PullRequests_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIWatcher_PullRequests_Call) RunAndReturn(run func(repository core.Repository)) *MockIWatcher_PullRequests_Call {
	_c.Run(run)
	return _c
}

// WorkflowRuns provides a mock function for the type MockIWatcher
func (_mock *MockIWatcher) WorkflowRuns(repository core.Repository) {
	_mock.Called(repository)
	return
}

// MockIWatcher_WorkflowRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkflowRuns'
type MockIWatcher_WorkflowRuns_Call struct {
	*mock.Call
}

// WorkflowRuns is a helper method to define mock.On call
//   - repository core.Repository
func (_e *MockIWatcher_Expecter) WorkflowRuns(repository interface{}) *MockIWatcher_WorkflowRuns_Call {
	return &MockIWatcher_WorkflowRuns_Call{Call: _e.mock.On("WorkflowRuns", repository)}
}

func (_c *MockIWatcher_WorkflowRuns_Call) Run(run func(repository core.Repository)) *MockIWatcher_WorkflowRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Repository
		if args[0] != nil {
			arg0 = args[0].(core.Repository)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIWatcher_WorkflowRuns_Call) Return() *MockIWatcher_WorkflowRuns_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIWatcher_WorkflowRuns_Call) RunAndReturn(run func(repository core.Repository)) *MockIWatcher_WorkflowRuns_Call {
	_c.Run(run)
	return _c
}
