{
 "title": "Github",
 "time": { "from": "now-1s", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "PullRequests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(repository_full_name) (pull_request_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Actions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(repository_full_name) (latest_workflows{conclusion=\"failure\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Actions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(repository_full_name) (latest_workflows{state=~\"in_progress\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued Actions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(repository_full_name) (latest_workflows{state=~\"queued\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting Actions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(repository_full_name) (latest_workflows{state=\"waiting\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}