apiVersion: v1
kind: ConfigMap
metadata:
  name: github-observer-config
data:
  common.json: |-
    {
      "secret": "{{ .Values.secret }}",
      "ssl": {
        "activate": {{ .Values.ssl.activate }},
        "cert": "{{ .Values.ssl.cert }}",
        "key": "{{ .Values.ssl.key }}"
      },
      "app": {
        "listenAddress": "{{ .Values.app.listenAddress }}",
        "trustedProxies": {{ .Values.app.trustedProxies }},
        "mode": "{{ .Values.app.mode }}",
        "watcher": {{ .Values.app.watcher }},
        "logs": [
          {{- range $index, $element := .Values.app.logs }}
          "{{ $element }}"
            {{- if lt $index (sub (len .Values.app.logs) 1) }},{{- end }}
          {{- end }}
        ],
        "executors": [
          {{- range $index, $element := .Values.app.executors }}
          "{{ $element }}"
            {{- if lt $index (sub (len .Values.app.executors) 1) }},{{- end }}
          {{- end }}
        ]
      },
      "repositories": "{{ .Values.repositories }}"
    }