apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-observer.fullname" . }}
  labels:
    {{- include "github-observer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "github-observer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "github-observer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: USER_UID
              value: "{{ .Values.env.USER_UID }}"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-observer-secret
                  key: GITHUB_TOKEN
          volumeMounts:
            {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap.name }}
        {{- end }}