apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullname }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullname }}
    spec:
      containers:
        - name: {{ .Values.fullname }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - {{- tpl (toYaml .) $ | nindent 14 }}
            {{- end }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.key }}
                  key: {{ .Values.secret.key }}
