apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-observer-ingress
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: github-observer.local
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: github-observer
                port:
                  number: 8080
            path: /