apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: github-observer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080