apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-observer.fullname" . }}
  labels:
    {{- include "github-observer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
  selector:
    {{- include "github-observer.selectorLabels" . | nindent 4 }}